### PR TITLE
feat(nfs-client-multiple): fix mount

### PR DESCRIPTION
**Pull request by zxq-bit**
**What this PR does**
- fix docker image
- fix deployment policy
- add logs
- fix mounter status

**why we need it**

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zxq-bit** [comment]
@pendoragon PTAL

**Comment by deyuanix** [comment]
@zxq-bit do you plan to patch upstream?

**Comment by pendoragon** [comment]
@ddysher probably not, this is more like adapting `nfs-client` provisioner to our product(to match the concept of storage service and such)

**Comment by deyuanix** [comment]
@pendoragon But the changes here do not seem to be specific to our environment, am I missing something?

**Comment by pendoragon** [comment]
@ddysher it is not specific to our environment. But the way we are doing it now is bit of hacky(directly mounting a directory exported by nfs in the provisioner pod running in privileged mode). We'd have to come up with a better way of doing this before sending out a patch(as privileged pod is discouraged IIUC). A proposal/issue could be a starting point maybe? WDYT

**Comment by zxq-bit** [comment]
@pendoragon 现在这个 repo 的东西怎么合并下？

https://github.com/caicloud/external-storage/pull/4 是这个 pr 的 cla 通过的版本，版本号也更新了下
/cc @liubog2008

**Comment by pendoragon** [comment]
所以这个 pr 还需要么？

**Comment by zxq-bit** [comment]
@pendoragon 这个 pr 应该是 2.5 版本实际使用的，这个最好能合

**Comment by deyuanix** [comment]
@zxq-bit @pendoragon 要更新一下 OWNERS

**Comment by pendoragon** [comment]
@zxq-bit @liubog2008 你们现在应该有 approve 的权限了

**Comment by zxq-bit** [comment]
@liubog2008 PTAL

**Pull request merged**
